title: ＞ RTヒゲブログ（試験運用中）
email: your-email@example.com
description: >-
  RTヒゲの情報を掲載

url: "http://127.0.0.1:4000"
baseurl: ""

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme

sass:
  sass_dir: assets/css